on:
  push:
    paths:
      - "y/**"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: update
        run: echo `date` >! x
      - name: commit
        run: |
          git add x
          git commit -m "updated"
          git push
