on:
  push:
    paths:
      - "y/**"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - name: update
        run: |
          echo `date` > x
          cat x
      - name: commit
        run: |
          git config user.email "${{ secrets.GIT_CONFIG_USER_EMAIL }}"
          git config user.name "${{ secrets.GIT_CONFIG_USER_NAME }}"
          git add x
          git commit -m "updated"
          git push
